# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 18b89eec84b9293b4d7222679cf6b0d499e9f44f16d3144fcae627e43da89d988fb481097f2f8acf6e1fef0cf5854e63e65948cebef1b1253d89d7ed15f07c39
  facebook_token: <%= ENV["FACEBOOK_TOKEN"] %>

test:
  secret_key_base: a894947442fbe7d05d7a5c561dffbdf3e6702daae7be9aa776bbfa0bfd4b581227b5bec115ea1e2a8845be4bd54fd0a0e12e14d928446c6532bc74126e917557
  facebook_token: <%= ENV["FACEBOOK_TOKEN"] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  facebook_token: <%= ENV["FACEBOOK_TOKEN"] %>
